### PR TITLE
Typeahead v2 merge

### LINKED ISSUE #103: my account updates
image

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**
Closes #103 #102 #82

### CODE REVIEW

**Comment by adamjonas** [comment]
Can we alphabetize these drop downs? 

Screenshot 2023-06-29 at 10 11 05 AM

**Comment by adamjonas** [comment]
Arrows don't work in navigating the pull down. Can we enable that with arrows for up and down and enter key to select, deselect?

**Comment by adamjonas** [comment]
This needs to be more obvious. Try green instead of grey for the add copy and a prompt like "Search or Add Author" in the input box

Screenshot 2023-06-29 at 10 38 45 AM

**Comment by adamjonas** [comment]
re #103 

I didn't reset my reviews but this
Screenshot 2023-06-29 at 10 47 08 AM

 doesn't match

Screenshot 2023-06-29 at 10 46 08 AM

Let's add the link and emojis. (copy in mock is wrong)

**Comment by adamjonas** [comment]
[This one](https://github.com/bitcointranscripts/transcription-review-front-end/pull/109#issuecomment-1613301464) can be a follow-up. The rest seems to have made it though I'd prefer the input box for speakers was "Search or add" rather than just search, but I see that you are reusing the component so I can live with it and wait to see if the users have an issue with it.

Let's get some code review and get this in.

**Review by Extheoisah — APPROVED** [review]

**Comment by Extheoisah** [comment]
Looks good! 👍

**Pull request merged**
