### PR TITLE
Moved save and submit button for more Visibilty

### LINKED ISSUE #254: Improve Visibility and Placement of "Save" and "Submit" Buttons in Transcript Editor
**Issue Description:**
[A user reported a significant issue](https://github.com/bitcointranscripts/bitcointranscripts/issues/376) with the current placement and visibility of the "Save" and "Submit" buttons in the transcript editor. Due to their inconspicuous location at the bottom of the page, users may overlook them. The lack of auto-save functionality exacerbates the problem, leading to potential data loss in the event of a browser crash.

**Proposed Solution:**
To address this issue and mitigate the risk of users losing their work, I suggest relocating the "Save" and "Submit" buttons to the top of the page. Specifically, positioning them on the left side of the line where the "Restore Original" button currently resides. This adjustment aims to enhance visibility and accessibility, making it easier for users to save their progress and submit their edits without the risk of overlooking these critical actions.

Note: Implementing auto-save functionality is a non-trivial task and will not be addressed in this particular enhancement. Discussions are underway to determine the best approach for incorporating auto-save as a future enhancement

### PR DESCRIPTION
**Pull request by 0tuedon**
This PR closes #254 
Moved the save and submit button to the top of the mark down editor.

Current  Visiblity
Screenshot 2024-02-07 at 18 22 45

TESTED!

### CODE REVIEW

**Review by kouloumos — APPROVED** [review]
ACK

**Comment by 0tuedon** [comment]
> ACK

Good to merge.

**Comment by kouloumos** [comment]
> Good to merge.

lgtm

**Comment by 0tuedon** [comment]
> > Good to merge.
> 
> lgtm

Merged to Dev

**Comment by 0tuedon** [comment]
> I still see it like before. Maybe it was not deployed?
> 
> Anyway, it's probably good to close [bitcointranscripts/bitcointranscripts#376](https://github.com/bitcointranscripts/bitcointranscripts/issues/376) as well.
> 


Hey @edilmedeiros , yh it's not merged to production yet.

**Pull request merged**
