### PR TITLE
fix: merge two alerts modal

### PR DESCRIPTION
**Pull request by 0tuedon**
Screenshot 2023-07-09 at 20 28 35

### CODE REVIEW

**Comment by 0tuedon** [comment]
#101  here is the Pr to solve this issue

**Comment by adamjonas** [comment]
I'd prefer to have the old 🚢 button back and put the where you are creating the PR text under that.

**Comment by 0tuedon** [comment]
> I'd prefer to have the old 🚢 button back and put the where you are creating the PR text under that.

Okay.

**Comment by 0tuedon** [comment]
Screenshot 2023-07-10 at 22 33 34

@adamjonas  does this work?

**Comment by adamjonas** [comment]
Can we center the ready to ship button so that it is online with the others please?

**Comment by 0tuedon** [comment]
> Can we center the ready to ship button so that it is online with the others please?
> 
> Have not tested but I'm good to merge after that change.

Thanks for  the feedback this has been fixed. 
Screenshot 2023-07-11 at 18 32 22

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
