### PR TITLE
Homepage improvements

### PR DESCRIPTION
**Pull request by Emmanuel-Develops**

### CODE REVIEW

**Comment by adamjonas** [comment]
When I first arrive at the site (not logged in) I see the queue then am redirected. I should just see the tutorial page.

**Comment by adamjonas** [comment]
Ack on the accordion arrow clicks.

Can we add this page to the /tutorial route and put that in the menu as well?

**Comment by Emmanuel-Develops** [comment]
> When I first arrive at the site (not logged in) I see the queue then am redirected. I should just see the tutorial page.

Yeah, I was divisive on which should be the default (tutorial or queue) before auth decides where to take the user.

What are your thoughts on a loading screen instead? 
The auth process takes some time and that leads to flashes if user is Signed in but default on tutorial page. With loading screen we prevent showing the user any page until authentication is complete

**Comment by Emmanuel-Develops** [comment]
> Ack on the accordion arrow clicks.
> 
> Can we add this page to the /tutorial route and put that in the menu as well?

The page does exist on "/tutorial" route, sure we can have that in the menu

**Review by Extheoisah — APPROVED** [review]

**Pull request merged**
