### PR TITLE
fix: add data empty text

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/72

### CODE REVIEW

**Comment by Extheoisah** [comment]
@adamjonas is this what you had in mind? this pr only changes the text from 'No Data' to specific messages -> "No Current Jobs" or "No Past Jobs"

**Review by Emmanuel-Develops — APPROVED** [review]

**Comment by Emmanuel-Develops** [comment]
> @adamjonas is this what you had in mind? this pr only changes the text from 'No Data' to specific messages -> "No Current Jobs" or "No Past Jobs"

Lets Get this merged.
Not showing the tables at all may not be ideal, as those are the only components on that page. For example, if a new user goes to their profile page everything will be blank if we don't display any tables. A "No current/past jobs" is quite explicit

**Comment by adamjonas** [comment]
It's fine for now. We can adjust as needed based on user feedback.

**Comment by adamjonas** [comment]
It's fine for now. We can adjust as needed based on user feedback.

**Pull request merged**
