### PR TITLE
feat: support arbitrary fields

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/266

This should work for any arbitrary meta data fields we add in the future. Provided they are of the format we currently support: plain string, array of strings and Date. But I do envision us adding boolean meta data some time in the future.

### CODE REVIEW

**Comment by Emmanuel-Develops** [comment]
Some arbitrary fields are still lost.
refer this pr: https://github.com/Emmanuel-Develops/bitcointranscripts/pull/68/files

**Review by Emmanuel-Develops — CHANGES_REQUESTED** [review]
Some arbitrary fields are still lost.
refer this pr: https://github.com/Emmanuel-Develops/bitcointranscripts/pull/68/files

**Comment by BalogunofAfrica** [comment]
@Emmanuel-Develops Please confirm your results of retesting

**Review by kouloumos — COMMENTED** [review]
"Arbitrary fields" are flexible data entries that can vary in name and content, allowing for the addition of custom metadata without the need of defining each one of them in the code.
If you need to define them in the code in order to be available then they are not arbitrary.

What I asked for in the linked issue is for all the metadata fields in the original transcript to be kept in the final transcript. You went with something more complicated but more flexible and that would be okay, only if it was actually working. Which is not.

I ran your PR on my local machine connected with the staginig db. I claimed [this transcript](https://raw.githubusercontent.com/bitcointranscripts/bitcointranscripts/master/chaincode-labs/chaincode-podcast/simple-taproot-channels.md) on staging. Then [I submitted the transcript](https://github.com/kouloumos/bitcointranscripts/pull/26/files), but the fields are still deleted.
**Can you please tell me how you tested this PR?** Maybe I should be doing something else?

**Good work with the commits**, it makes it easier to understand the changes. That said, it could still be better, here are few suggestions to take into consideration for future PRs:
- When fixing something you should squash that change in the appropriate prior commit. Otherwise, while I am reviewing commit per commit I see code that gets added and then changed and deleted. That doesn't help me as a reviewer. That means that your last 5 commits should not be there but squashed into prior commits.

**Observations on the UI**:
- I prefer that now the sidebar has the same height as the editor and it allows for scrolling.
- The category dropdown doesn't show a hand as mouse pointer when hovering
- If I click on the speaker dropdown, and then I close the dropdown by clicking on it (not by clicking somewhere else) then the category dropdown cannot open.
Screencastfrom2024-04-0815-53-43-ezgif com-video-to-gif-converter

**Comment by BalogunofAfrica** [comment]
@kouloumos I noticed the deployments are been cached. I had a console on the client side to intro spect during submission and it doesn't get fired.

For the changes, the some data for some meta data like string JSON arrays gets lost when we try to submit, and this is because they `reconcileArray` function which we use for other JSON arrays like `categories` and `speakers` is too tied to their implementation. Also some other metadata were not been added to the metadata class which is part of the payload we send to github, hence also lost in transit

**Comment by kouloumos** [comment]
> @kouloumos I noticed the deployments are been cached. I had a console on the client side to intro spect during submission and it doesn't get fired.
> 
> For the changes, the some data for some meta data like string JSON arrays gets lost when we try to submit, and this is because they `reconcileArray` function which we use for other JSON arrays like `categories` and `speakers` is too tied to their implementation. Also some other metadata were not been added to the metadata class which is part of the payload we send to github, hence also lost in transit

I wish I could say that I understood what you are trying to say.

So, in my previous test, the PR wasn't working as expected. You pushed some changes. Should the PR work now and solve the problem that is supposed to be solving?

**Pull request closed without merging**
