### PR TITLE
Fix: updating html to readme instead of markdown

### PR DESCRIPTION
**Pull request by 0tuedon**

### CODE REVIEW

**Comment by Extheoisah** [comment]
You need to rebase on dev branch to fix the conflict

**Review by Emmanuel-Develops — COMMENTED** [review]
Looks good!
You can cleanup the git history a bit, so only the new commit e847737 and c5391bf should be rebased on dev from this branch.

From the top of my head you can try git reset to c5391bf, then git rebase the dev branch. Might have to force push

**Comment by 0tuedon** [comment]
Resolving conflicts

**Comment by 0tuedon** [comment]
> You need to rebase on dev branch to fix the conflict

yh i saw that now, would effect

**Comment by 0tuedon** [comment]
@Extheoisah  @Emmanuel-Develops  does this work now?

**Comment by Extheoisah** [comment]
Just tested it and the problem persists. See here -> https://github.com/Extheoisah/bitcointranscripts/pull/3/files 

You need to setup your guthub webhook so you can test locally. I think @Emmanuel-Develops documented it somewhere, cant remember

**Comment by 0tuedon** [comment]
> 

okay would check. @Emmanuel-Develops  can you point towards that

**Comment by 0tuedon** [comment]
> Just tested it and the problem persists. See here -> https://github.com/Extheoisah/bitcointranscripts/pull/3/files 
> 
> You need to set up your GitHub webhook so you can test locally. I think @Emmanuel-Develops documented it somewhere, can't remember 

https://github.com/0tuedon/bitcointranscripts/pull/1
Tested here

**Comment by 0tuedon** [comment]
@Extheoisah  a second test, also changed
The speakers, tags, categories as well as with markdown elements

https://github.com/0tuedon/bitcointranscripts/pull/2

**Review by Extheoisah — APPROVED** [review]

**Pull request closed without merging**
