### PR TITLE
feat: admin archive

### PR DESCRIPTION
**Pull request by BalogunofAfrica**
Closes https://github.com/bitcointranscripts/transcription-review-front-end/issues/11

### CODE REVIEW

**Comment by adamjonas** [comment]
How do I make myself an admin to check this?

**Comment by BalogunofAfrica** [comment]
This is how it looks like when selecting transcripts from the index page to archive @adamjonas 

Before batch select:
Screenshot 2023-04-19 at 22 36 14


After select:
Screenshot 2023-04-19 at 22 36 27

**Comment by adamjonas** [comment]
Tested and works fine noting it's not hooked up to the backend. @Emmanuel-Develops is any of this going to conflict with your PR?

**Comment by Emmanuel-Develops** [comment]
> Tested and works fine noting it's not hooked up to the backend. @Emmanuel-Develops is any of this going to conflict with your PR?

I can't see any conflicts. It should be fine

**Pull request merged**
