### PR TITLE
Fix: same branch on resubmit error

### PR DESCRIPTION
**Pull request by 0tuedon**

### CODE REVIEW

**Review by Emmanuel-Develops — CHANGES_REQUESTED** [review]
looks good, but there isn't clear separation between handling the two cases i.e updating an existing PR and creating a new PR.

Pull all general functions at the top of the `createForkAndPR` block.
Then after you get pull_number you can proceed with the condiotional for if `pr_number`.

Also put the previous logic for generating new branch and create PR into a separate function. This is useful because in the `pull_number` `if` block you can have a try catch that surrounds it's content then for some specific errors you can call the previous logic as a fallback i.e "in case you can't update that specific PR, simply create a new branch and create another PR"

I don't know how well we can handle 2 open PRs, so lets leave the fallback for now

**Comment by Emmanuel-Develops** [comment]
@adamjonas what are your thoughts regarding a fallback of creating a new branch in case of an error when updating the pr?

**Comment by adamjonas** [comment]
can you give me an example on why that might occur?

**Comment by Emmanuel-Develops** [comment]
> can you give me an example on why that might occur?

@adamjonas 
there should be two cases:
- on invalid url from db. This should mostly be a non-issue.
- and if the pr is merged or closed. This updates the branch so there really isn't an issue here.

On writing this it became apparent to me we aren't checking for PR status (open, merged, closed) before updating PR branch.
We need to account for it. If the PR has been closed they can always claim the transcript again since it has been returned to the queue.

This is getting to be a spiral, but it also became apparent we do not have a middleware to ensure only those who have an active review with that transcriptId can update that transcript.

Since the PR logic and save logic are different (we first save then open PR), the `save` should fail if they are updating a transcript in a review that has been merged

this is quite a spiral, here's the summary: 
- It appears there isn't any major case where we need a fallback.
- we need to ensure the PR is open (!merged && !closed) before updating the PR branch @0tuedon 
- we need to include a middleware (for update transcript route) that only a reviewer that has an active review attached to that transcriptId can update that transcript. (I'll write an issue for this)

@Extheoisah we didn't add the middleware to review routes

**Comment by adamjonas** [comment]
Ok. Sounds like the addition of a closed or merged check should suffice and we can harden it up later. Let's keep it simple for now.

**Review by Emmanuel-Develops — APPROVED** [review]

**Pull request merged**
